export const USER_AUTHENTICATION_SUCCESS = "USER_AUTHENTICATION_SUCCESS";
export const USER_AUTHENTICATION_FAILURE = "USER_AUTHENTICATION_FAILURE";
export const TOGGLE_LOGIN_SIGNUP = "TOGGLE_LOGIN_SIGNUP"