export const AUTO_COMPLETE_FROM_AREA = "AUTO_COMPLETE_FROM_AREA";
export const AUTO_COMPLETE_TO_AREA = "AUTO_COMPLETE_TO_AREA";
export const AUTO_COMPLETE_VIAPOINT = "AUTO_COMPLETE_VIAPOINT";
export const AUTO_COMPLETE_CHECKPOINT = "AUTO_COMPLETE_CHECKPOINT";
export const FAILURE = "FAILURE";