export const FROM_AUTO_COMPLETE_SUCCESS = "FROM_AUTO_COMPLETE_SUCCESS";
export const FROM_AUTO_COMPLETE_FAILURE = "FROM_AUTO_COMPLETE_FAILURE";
export const TO_AUTO_COMPLETE_SUCCESS = "TO_AUTO_COMPLETE_SUCCESS";
export const TO_AUTO_COMPLETE_FAILURE = "TO_AUTO_COMPLETE_FAILURE";
export const VIAPOINT_AUTO_COMPLETE_SUCCESS = "VIAPOINT_AUTO_COMPLETE_SUCCESS";
export const VIAPOINT_AUTO_COMPLETE_FAILURE = "VIAPOINT_AUTO_COMPLETE_FAILURE";
export const CHECKPOINT_AUTO_COMPLETE_SUCCESS = "CHECKPOINT_AUTO_COMPLETE_SUCCESS";
export const CHECKPOINT_AUTO_COMPLETE_FAILURE = "CHECKPOINT_AUTO_COMPLETE_FAILURE";