export const CREATE_CAR_SUCCESS = "CREATE_CAR_SUCCESS"
export const CREATE_CAR_FAILURE = "CREATE_CAR_FAILURE"
export const CHECK_CAR_PRESENT_SUCCESS = "CHECK_CAR_PRESENT_SUCCESS"
export const CHECK_CAR_PRESENT_FAILURE = "CHECK_CAR_PRESENT_FAILURE"
