export const CREATE_RIDE_OFFER_SUCCESS = "CREATE_RIDE_OFFER_SUCCESS"
export const CREATE_RIDE_OFFER_FAILURE = "CREATE_RIDE_OFFER_FAILURE"
export const FETCH_ALL_RIDE_OFFERS_SUCCESS = "FETCH_ALL_RIDE_OFFERS_SUCCESS"
export const FETCH_ALL_RIDE_OFFERS_FAILURE = "FETCH_ALL_RIDE_OFFERS_FAILURE"
